!FELIPE GM - MOD7 COMPUTER ARCHITECTURE CONCORDIA CONTINUING EDUCATION
!FINAL ASSIGNMENT FOR THE FALL CLASS 2022
!EXAMPLE OF A SIMPLE ASSEMBLY PROGRAM USING A FEW INSTRUCTIONS. ANY LINE STARTING WITH '!' IS A COMMENT
!THE FIRST PART OF THE FILE IS THE DATA DECLARATION, STARTING WITH #DATA. ANY VARIABLE HAS A UNIQUE TYPE OF SIZE 32BITS AND SHOULD BE INITIALIZED TO A VALUE

#DATA
A 10
B 15
RES 0

!NEXT, WE START THE CODE WITH THE #CODE MACRO
#CODE
LDA T0 A
LDA T1 B
HLT
ADD T0 T1
STR RES T0
HLT